### ISSUE TITLE
how get the release files from azure 

### ISSUE THREAD

**Issue by hongwei7458** [MicrosoftDocs/pipelines-dotnet-core#29]
when i  release project ,how to get release files from azure

**Comment by vijayma** [comment]
Please review the docs here: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azure-devops&tabs=yaml and https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml. If you still have questions, then please open an issue on those corresponding docs.
