### ISSUE TITLE
[error]Bash wrote one or more lines to the standard error stream.

### ISSUE THREAD

**Issue by linuschew** [MicrosoftDocs/pipelines-dotnet-core#31]
Error when running pipeline using azure-pipelines.yml

commented out failOnStderr: true and it works

**Comment by I-Sokolov** [comment]
You may comment dotnetcore-tests/UnitTest1.cs:line 35 to suspend the error

**Comment by vijayma** [comment]
Updated the sample repo to work out of the box.
