### ISSUE TITLE
Please provide sample for .NET Core 3.1

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/pipelines-dotnet-core#55]
Now where .NET Core 2.2 is out of support, it would be great if the  .NET Core sample could be updated to the latest LTS version (3.1).

**Comment by NicolasReyDotNet** [comment]
@vijayma @vijaymatest1 
Hi, could you provide 3.1 sample ?

Thank you for your amazing work!

**Comment by aluevano** [comment]
I've modified the sample to the LTS version (pending pull request)

**Comment by NicolasREY69330** [comment]
Thank you, I'll update my code based on your best practices
