### ISSUE TITLE
.Net core task restore does not use custom nuget.config file

### ISSUE THREAD

**Issue by minhhungit** [MicrosoftDocs/pipelines-dotnet-core#89]
Hello team, I found this repo from this link https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive

I guess this repo handle issue of ".net core" pipeline task, if I was wrong, pls correct me.

Problem I want to report is ".NET CORE" pipe task does not use custom nuget.config file, this is what I configured

![image](https://user-images.githubusercontent.com/2279508/123591983-dd620200-d816-11eb-95b9-d4eccb160d70.png)

And this is log:

>C:\hostedtoolcache\windows\dotnet\dotnet.exe restore D:\a\1\s\XXXX.XXXX.XXXX.Web.csproj --configfile D:\a\1\Nuget\tempNuGet_1102.config --no-cache --verbosity Detailed

It is using `tempNuGet_1102.config` not my file `Nuget.Full.config` from main folder of my solution

Is this a bug, if it is, please show me how can I do a quick-fix this

Thank you

**Comment by minhhungit** [comment]
After using `Arguments` textbox to pass location of custom nuget.config , the log show this

```
C:\hostedtoolcache\windows\dotnet\dotnet.exe restore D:\a\1\s\XXX\XXX.Web.csproj --configfile D:\a\1\Nuget\tempNuGet_1104.config --no-cache --verbosity Detailed --configfile D:\a\1\s\NuGet.Full.config
```

![image](https://user-images.githubusercontent.com/2279508/123593173-69285e00-d818-11eb-9d9d-7117d11db8a1.png)

![image](https://user-images.githubusercontent.com/2279508/123593312-8f4dfe00-d818-11eb-9eba-5e5e438b5014.png)

**Comment by minhhungit** [comment]
It work after I convert UI => yml

```yaml
  - task: DotNetCoreCLI@2
    displayName: restore web project with NuGet.Full.config
    inputs:
      command: 'restore'
      projects: 'MediaObjects.Web/MediaObjects.Web.csproj'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.Full.config'
```

**Actually there is another problem**, my `NuGet.Full.config` contain a custom nuget source which is a folder on repository for example: `my-pro-packages`

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <!-- remove any machine-wide sources with <clear/> -->
        <clear />
        
        <add key="MyProPackages" value="my-pro-packages" />
        <add key="AnotherPackages" value="https://abc.xyz/nuget/v3/index.json" />
        <add key="NuGet Official" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
        
    </packageSources>
</configuration>
```

It said that: `The local source 'D:\a\1\Nuget\my-pro-packages' doesn't exist`

So I have to push my-pro-packages *.nupkg files to artifacts to use

**Comment by juliakm** [comment]
@minhhungit Sorry for the delay in responding. You can report issues with specific tasks in this repository - https://github.com/microsoft/azure-pipelines-tasks.
